{% set build = 1008 %}
{% set version = "4.0.3" %}
{% set sha256 = "f2d9a231b7cf97f1fee6e8c9663113ebf6c240d407d3c118c55b3633d6be6e5f" %}

{% set mpi = mpi or 'mpich' %}

package:
  name: parmetis
  version: {{ version }}

source:
  url: https://karypis.github.io/glaros/files/sw/parmetis/parmetis-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  skip: true  # [win]
  number: {{ build }}
  run_exports:
    - {{ pin_subpackage("parmetis", max_pin="x.x") }}

requirements:
  build:
    - cmake
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
    - make
    - {{ mpi }}   # [mpi == "openmpi" and build_platform != target_platform]
  host:
    - {{ mpi }}
  run:
    - {{ mpi }}

test:
  commands:
    - test -f "${PREFIX}/include/parmetis.h"
    - test -f "${PREFIX}/lib/libparmetis.dylib"  # [osx]
    - test -f "${PREFIX}/lib/libparmetis.so"  # [linux]

about:
  home: http://glaros.dtc.umn.edu/gkhome/metis/parmetis/overview
  license: LicenseRef-ParMETIS
  license_file: LICENSE.txt
  license_url: https://github.com/KarypisLab/ParMETIS/blob/main/LICENSE
  summary: 'ParMETIS - Parallel Graph Partitioning and Fill-reducing Matrix Ordering'
  description: |
    ParMETIS is an MPI-based parallel library that implements a
    variety of algorithms for partitioning unstructured graphs,
    meshes, and for computing fill-reducing orderings of sparse
    matrices. ParMETIS extends the functionality provided by METIS and
    includes routines that are especially suited for parallel AMR
    computations and large scale numerical simulations. The algorithms
    implemented in ParMETIS are based on the parallel multilevel k-way
    graph-partitioning, adaptive repartitioning, and parallel
    multi-constrained partitioning schemes developed in our lab.
  doc_url: http://glaros.dtc.umn.edu/gkhome/fetch/sw/parmetis/manual.pdf
  dev_url: https://github.com/KarypisLab/ParMETIS

extra:
  recipe-maintainers:
    - basnijholt
    - dalcinl
    - isuruf
    - minrk
    - davidbrochart
